ALTER TABLE playlists    ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE contributors ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE songs        ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE nominations  ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1;
