import { Amplify } from 'aws-amplify'
import outputs from '../amplify_outputs.json'

// amplify_outputs.json is generated by `npx ampx sandbox` / `npx ampx pipeline-deploy` (run
// from ui/, see ui/amplify/backend.ts) — it's committed with placeholder values so local
// type-checking/builds work before a first real deploy, then overwritten by every deploy.
// Do not hand-edit it.
Amplify.configure(outputs)
