package com.orgasm.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

/**
 * Minimal stub satisfying the ApiClient.valueToString()/urlEncode() references
 * generated by openapi-generator in each model's toUrlQueryString() helper
 * method. The full ApiClient (HTTP transport) lives in each SDK module
 * separately. urlEncode() mirrors the real generated ApiClient's
 * implementation (Java/libraries/native/ApiClient.mustache) so behavior stays
 * identical across generator upgrades.
 */
public class ApiClient {

    public static String valueToString(Object value) {
        if (value == null) {
            return "";
        }
        return value.toString();
    }

    public static String urlEncode(String s) {
        return URLEncoder.encode(s, StandardCharsets.UTF_8).replaceAll("\\+", "%20");
    }
}
